### ISSUE TITLE
Does not work with pytest 3.3.0

### ISSUE THREAD

**Issue by blueyed** [abusalimov/pytest-travis-fold#4]
```
% tox -e py36
GLOB sdist-make: …/Vcs/pytest-travis-fold/setup.py
py36 create: …/Vcs/pytest-travis-fold/.tox/py36
py36 installdeps: pytest
py36 inst: …/Vcs/pytest-travis-fold/.tox/dist/pytest-travis-fold-1.2.0.zip
py36 installed: attrs==17.3.0,pluggy==0.6.0,py==1.5.2,pytest==3.3.0,pytest-travis-fold==1.2.0,six==1.11.0
py36 runtests: PYTHONHASHSEED='2639477772'
py36 runtests: commands[0] | py.test tests
==================================== test session starts ====================================
platform linux -- Python 3.6.3, pytest-3.3.0, py-1.5.2, pluggy-0.6.0
rootdir: …/Vcs/pytest-travis-fold, inifile:
plugins: travis-fold-1.2.0
collected 10 items                                                                          

tests/test_fixture.py ........                                                        [ 80%]
tests/test_travis_fold.py FF                                                          [100%]

========================================= FAILURES ==========================================
____________________________________ test_no_travis_env _____________________________________

failtest = <bound method Testdir.runpytest of <Testdir local('/tmp/pytest-of-user/pytest-469/test_no_travis_env0')>>
monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7fee231256d8>

    def test_no_travis_env(failtest, monkeypatch):
        """Check cmdline options on a dev env (no TRAVIS variable)."""
        monkeypatch.delenv('TRAVIS', raising=False)
    
        with pytest.raises(pytest.fail.Exception):
            failtest().stdout.fnmatch_lines(travis_lines)
        with pytest.raises(pytest.fail.Exception):
            failtest('--travis-fold=auto').stdout.fnmatch_lines(travis_lines)
    
>       failtest('--travis-fold=always').stdout.fnmatch_lines(travis_lines)

…/Vcs/pytest-travis-fold/tests/test_travis_fold.py:31: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <_pytest.pytester.LineMatcher object at 0x7fee22bfb668>
lines2 = ['travis_fold:start:*', 'travis_fold:end:*']

    def fnmatch_lines(self, lines2):
        """Search captured text for matching lines using ``fnmatch.fnmatch``.
    
            The argument is a list of lines which have to match and can
            use glob wildcards.  If they do not match a pytest.fail() is
            called.  The matches and non-matches are also printed on
            stdout.
    
            """
>       self._match_lines(lines2, fnmatch, 'fnmatch')
E       Failed: nomatch: 'travis_fold:start:*'
E           and: '============================= test session starts =============================='
E           and: 'platform linux -- Python 3.6.3, pytest-3.3.0, py-1.5.2, pluggy-0.6.0'
E           and: 'rootdir: /tmp/pytest-of-user/pytest-469/test_no_travis_env0, inifile:'
E           and: 'plugins: travis-fold-1.2.0'
E           and: 'collected 1 item'
E           and: ''
E           and: 'test_no_travis_env.py F                                                  [100%]'
E           and: ''
E           and: '=================================== FAILURES ==================================='
E           and: '___________________________________ test_sth ___________________________________'
E           and: ''
E       remains unmatched: 'travis_fold:start:*'

…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/_pytest/pytester.py:1139: Failed
----------------------------------- Captured stdout call ------------------------------------
============================= test session starts ==============================
platform linux -- Python 3.6.3, pytest-3.3.0, py-1.5.2, pluggy-0.6.0
rootdir: /tmp/pytest-of-user/pytest-469/test_no_travis_env0, inifile:
plugins: travis-fold-1.2.0
collected 1 item

test_no_travis_env.py F                                                  [100%]

=================================== FAILURES ===================================
___________________________________ test_sth ___________________________________

    def test_sth():
        print('boo!')
>       assert False
E       assert False

test_no_travis_env.py:3: AssertionError
----------------------------- Captured stdout call -----------------------------
boo!
=========================== 1 failed in 0.02 seconds ===========================
============================= test session starts ==============================
platform linux -- Python 3.6.3, pytest-3.3.0, py-1.5.2, pluggy-0.6.0
rootdir: /tmp/pytest-of-user/pytest-469/test_no_travis_env0, inifile:
plugins: travis-fold-1.2.0
collected 1 item

test_no_travis_env.py F                                                  [100%]

=================================== FAILURES ===================================
___________________________________ test_sth ___________________________________

    def test_sth():
        print('boo!')
>       assert False
E       assert False

test_no_travis_env.py:3: AssertionError
----------------------------- Captured stdout call -----------------------------
boo!
=========================== 1 failed in 0.00 seconds ===========================
============================= test session starts ==============================
platform linux -- Python 3.6.3, pytest-3.3.0, py-1.5.2, pluggy-0.6.0
rootdir: /tmp/pytest-of-user/pytest-469/test_no_travis_env0, inifile:
plugins: travis-fold-1.2.0
collected 1 item

test_no_travis_env.py F                                                  [100%]

=================================== FAILURES ===================================
___________________________________ test_sth ___________________________________
----------------------------------- Captured stderr call ------------------------------------
Traceback (most recent call last):
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/_pytest/pytester.py", line 738, in runpytest_inprocess
    reprec = self.inline_run(*args, **kwargs)
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/_pytest/pytester.py", line 711, in inline_run
    ret = pytest.main(list(args), plugins=plugins)
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/_pytest/config.py", line 59, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
    return outcome.get_result()
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/_pytest/main.py", line 134, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/_pytest/main.py", line 128, in wrap_session
    exitstatus=session.exitstatus)
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/__init__.py", line 182, in __call__
    return outcome.get_result()
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 48, in from_call
    result = func()
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/__init__.py", line 180, in <lambda>
    outcome = _Result.from_call(lambda: self.oldcall(hook, hook_impls, kwargs))
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 196, in _multicall
    gen.send(outcome)
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/_pytest/terminal.py", line 464, in pytest_sessionfinish
    self.summary_failures()
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/_pytest/terminal.py", line 588, in summary_failures
    self._outrep_summary(rep)
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pytest_travis_fold.py", line 197, in patched_outrep_summary
    rep.toterminal(reporter.writer)
AttributeError: 'TerminalReporter' object has no attribute 'writer'
______________________________________ test_travis_env ______________________________________

failtest = <bound method Testdir.runpytest of <Testdir local('/tmp/pytest-of-user/pytest-469/test_travis_env0')>>
monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7fee22bf3400>

    def test_travis_env(failtest, monkeypatch):
        """Set TRAVIS=true and check the stdout section is properly wrapped."""
        monkeypatch.setenv('TRAVIS', 'true')
    
>       failtest().stdout.fnmatch_lines(travis_lines)

…/Vcs/pytest-travis-fold/tests/test_travis_fold.py:41: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <_pytest.pytester.LineMatcher object at 0x7fee23106cc0>
lines2 = ['travis_fold:start:*', 'travis_fold:end:*']

    def fnmatch_lines(self, lines2):
        """Search captured text for matching lines using ``fnmatch.fnmatch``.
    
            The argument is a list of lines which have to match and can
            use glob wildcards.  If they do not match a pytest.fail() is
            called.  The matches and non-matches are also printed on
            stdout.
    
            """
>       self._match_lines(lines2, fnmatch, 'fnmatch')
E       Failed: nomatch: 'travis_fold:start:*'
E           and: '============================= test session starts =============================='
E           and: 'platform linux -- Python 3.6.3, pytest-3.3.0, py-1.5.2, pluggy-0.6.0'
E           and: 'rootdir: /tmp/pytest-of-user/pytest-469/test_travis_env0, inifile:'
E           and: 'plugins: travis-fold-1.2.0'
E           and: 'collected 1 item'
E           and: ''
E           and: 'test_travis_env.py F                                                     [100%]'
E           and: ''
E           and: '=================================== FAILURES ==================================='
E           and: '___________________________________ test_sth ___________________________________'
E           and: ''
E       remains unmatched: 'travis_fold:start:*'

…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/_pytest/pytester.py:1139: Failed
----------------------------------- Captured stdout call ------------------------------------
============================= test session starts ==============================
platform linux -- Python 3.6.3, pytest-3.3.0, py-1.5.2, pluggy-0.6.0
rootdir: /tmp/pytest-of-user/pytest-469/test_travis_env0, inifile:
plugins: travis-fold-1.2.0
collected 1 item

test_travis_env.py F                                                     [100%]

=================================== FAILURES ===================================
___________________________________ test_sth ___________________________________
----------------------------------- Captured stderr call ------------------------------------
Traceback (most recent call last):
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/_pytest/pytester.py", line 738, in runpytest_inprocess
    reprec = self.inline_run(*args, **kwargs)
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/_pytest/pytester.py", line 711, in inline_run
    ret = pytest.main(list(args), plugins=plugins)
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/_pytest/config.py", line 59, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
    return outcome.get_result()
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/_pytest/main.py", line 134, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/_pytest/main.py", line 128, in wrap_session
    exitstatus=session.exitstatus)
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/__init__.py", line 182, in __call__
    return outcome.get_result()
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 48, in from_call
    result = func()
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/__init__.py", line 180, in <lambda>
    outcome = _Result.from_call(lambda: self.oldcall(hook, hook_impls, kwargs))
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 196, in _multicall
    gen.send(outcome)
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/_pytest/terminal.py", line 464, in pytest_sessionfinish
    self.summary_failures()
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/_pytest/terminal.py", line 588, in summary_failures
    self._outrep_summary(rep)
  File "…/Vcs/pytest-travis-fold/.tox/py36/lib/python3.6/site-packages/pytest_travis_fold.py", line 197, in patched_outrep_summary
    rep.toterminal(reporter.writer)
AttributeError: 'TerminalReporter' object has no attribute 'writer'
============================ 2 failed, 8 passed in 0.24 seconds =============================
ERROR: InvocationError: '…/Vcs/pytest-travis-fold/.tox/py36/bin/py.test tests'
__________________________________________ summary __________________________________________
ERROR:   py36: commands failed
tox -e py36  5.23s user 0.48s system 83% cpu 6.820 total
```

Haven't investigated - hopefully the fix is simple/trivial?!

**Comment by abusalimov** [comment]
@blueyed Thanks for reporting!

I afraid, I can't estimate when I'm going to have some spare time to investigate it either. I guess it shouldn't be that complicated indeed. If it happens that you find the cause, please feel free to open a PR!
